### ISSUE TITLE
Proposal: Refactor MakeRequest

### ISSUE THREAD

**Issue by natebrennand** [underarmour/dynago#10]
Currently [`MakeRequest`](https://github.com/underarmour/dynago/blob/master/internal/aws/api_request.go#L37-L64) returns a byte array and relies on AWS setting the `ContentLength` header in their response. I've encountered a scenario where Amazon returns a large amount of data (a `Scan` request) and fails to set the `ContentLength` header. I dumped the contents of the request and it had all the data requested. 

Technically this is a Amazon issue but I think utilizing encoders from `json` will alleviate it. The Local DynamoDB instance is more consistent in setting all the necessary headers which is why your tests haven't caught this.

I'd like to change `MakeRequest` to return a `io.ReadCloser` and let `json.Decoder` handle the body. I'm going to implement this change.

This is just a headsup in case you have any thoughts on it. All the changes are internal so there would be no interface errors.

**Comment by crast** [comment]
Well, the MakeRequest is actually a [public interface](http://godoc.org/gopkg.in/underarmour/dynago.v1#AwsRequester), even if the only current implementation is internal... but that's not actually my concern, since I think I can safely say at this point it can be changed without affecting anyone... the internals of AwsExecutor only got exposed about a week ago, and I doubt anyone would have already written their own implementation.

My bigger concern is passing an unbounded io.ReadCloser to json.Unmarshal... a bad response could in theory run you out of memory.

What would probably be safer if `response.ContentLength` is un-set, is to set a maximum amount we're going to read into a byte slice, and then read that amount, thus preventing the chance that you can get OOM'ed or waste time reading garbage.

**Comment by natebrennand** [comment]
Oops, had not realized that when I filed this. Well I've already done a potential fix that seems to work for my API call at the very least (https://github.com/underarmour/dynago/pull/12).

**Comment by natebrennand** [comment]
What if the maximum amount set was less than a valid response received?

**Comment by crast** [comment]
I would say then our maximum was set incorrectly or amazon violated their own contract.

In either case, I think it's an error condition? In the various API calls, amazon specifies how big the maximum response will be, e.g 1MB for Query and Scan calls: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html

We can set the limit to 5MB or even more to be safe, and not run into any issue for a long time.

**Comment by natebrennand** [comment]
I think we could avoid the extra allocation and still have the safety of a limit if we wrapped the reader passed to `json.Encoder` with a [`LimitedReader`](http://golang.org/pkg/io/#LimitedReader)
